# Generated by Django 6.0.4 on 2026-05-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
